### ISSUE TITLE
Can you move this repo to pantsbuild?

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/rbe-token-server#1]
Since this project is intended for pantsbuild/pants to use it seems to make sense for discoverability by contributors to move the repo there. In so doing, its fine to keep it private to members of pants committers.

**Comment by Eric-Arellano** [comment]
Agreed, but Stu found we can't do this quite yet because Pants doesn't pay GitHub so it can't have any private repos.

The plan is to make this public once we get confirmation from Google that we are allowed to have the below lines public:

https://github.com/Eric-Arellano/rbe-token-server/blob/62082c5882a599f4e665692edb05e7c4d4bc6aea/src/server.py#L11-L19

I'm waiting to hear back from Daniel who our Google liaison is to answer this.

**Comment by jsirois** [comment]
This is now complete!
